feat: add APIs to easily test the Pino logger
pinojs/pino-test pull request #1
Opened 2024-03-09 13:19 UTC by ruddenchaux

2024-03-09 13:40 UTC, jsumners requested changes

2024-03-09 13:40 UTC, jsumners commented on package-lock.json
Please remove this file.

2024-03-09 13:40 UTC, jsumners commented on package.json
> +    "jest": "^29.7.0",
We use either `tap` or `node:test`. We do not use `jest`.

2024-03-09 13:40 UTC, jsumners commented on package.json
> +    "pre-commit": "^1.2.2",
This should be `@fastify/pre-commit`.

2024-03-09 13:40 UTC, jsumners commented on README.md
> +A set of API to easily test the Pino logger.
```suggestion
Provides a set of utilities for verifying logs generated by the Pino logger.
```

2024-03-09 13:40 UTC, jsumners commented on README.md
> +```
This whole block is redundant. It doesn't seem to show anything unique about using `jest` over `tap` or `node:test`.

2024-03-09 13:40 UTC, jsumners commented on README.md
> +```
The only difference between this example and the `node:test` example is the including of a second test that utilizes a custom assertion function. I think we can move that example into the `node:test` block and completely remove the `tap` example as it is redundant.

2024-03-09 14:46 UTC, jsumners approved these changes

2024-03-10 08:12 UTC, mcollina approved these changes
lgtm

2024-03-13 09:41 UTC, merged

2024-03-13 09:41 UTC, mcollina commented
Thank you very much!

2024-03-13 11:14 UTC, ruddenchaux commented
It is a pleasure, thank you for the code reviews!